baseURL = "https://scic.sports.gouv.fr"
DefaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "Scic"
description = "Un outil de l'économie sociale et solidaire pour le développement du sport"

[extra]
live_base_url = "https://scic.sports.gouv.fr"

[[menu.main]]
  name = "Diagnostic"
  weight = 1
  identifier = "diagnostic"
  url = "/diagnostic/"
[[menu.main]]
  name = "La SCIC c'est"
  weight = 1
  identifier = "about"
  url = "/a-propos/"   
[[menu.main]]
  name = "Outils et ressources"
  weight = 1
  identifier = "tools_ressources"
  url = "/outils-et-ressources/"   
[[menu.main]]
  name = "Guide (pdf de 1.4 Mo)"
  weight = 10
  identifier = "guide" 
  url = "/pdf/guide-scic.pdf" 

[Params]
  ghrepo = "https://github.com/jonathanulco/SCIC"
  branch = "master"

[outputs]
home = [ "HTML", "RSS", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""


[outputFormats]
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true 
