[build]
  HUGO_VERSION = "0.55.5"
  publish = "public"
  command = "hugo --buildDrafts --templateMetrics --templateMetricsHints"

[context.production.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.6"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.55.6"