backend:
  name: github
  repo: jonathanulco/SCIC
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/" # The src attribute for uploaded media will begin with /images/uploads

collections:

  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "description"
        name: "description"
        required: true
        widget: "string"

      - label: "Cover Image"
        name: "image"
        required: false
        widget: "image"
        default: "/images/lorem-image.jpg"

      - label: "Body"
        name: "body"
        widget: "markdown"
